name: Run ask_gemini.py every hour

on:
  schedule:
    - cron: '0 * * * *'  # 매시간 정각마다 실행
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python ask_gemini.py

      - name: Commit and Push result.txt
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global user.email "rimblee2000@gmail.com"
          git config --global user.name "JUNBUNG-droid"

          if [ -f result.txt ]; then
            git add result.txt
            git commit -m "Update result.txt" || echo "No changes to commit"
            git push https://x-access-token:${GIT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${BRANCH_NAME}
          else
            echo "result.txt 파일이 존재하지 않습니다."
          fi
