name: Run ask_gemini.py every hour

on:
  schedule:
    - cron: '0 * * * *'  # 매시간 정각마다 실행
  workflow_dispatch:      # 수동으로도 실행 가능

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Python 버전 (필요하면 3.10 등으로 변경 가능)

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python ask_gemini.py

      - name: Commit result.txt
        run: |
          git config --global user.email rimblee2000@gmail.com
          git config --global user.name "JUNBUNG-droid"
          git add result.txt
          git commit -m "Update result.txt"
          git push
