name: Run ask_gemini.py every hour

on:
  schedule:
    - cron: '0 * * * *'  # 매시간 정각마다 실행
  workflow_dispatch:      # 수동으로도 실행 가능

permissions:
  contents: write  # 저장소 내용 수정 권한 설정
  actions: read    # 액션 수정 권한 설정

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python ask_gemini.py

      - name: Ensure git is initialized and commit result.txt
        run: |
          # Git 초기화 및 사용자 설정
          git config --global user.email "rimblee2000@gmail.com"
          git config --global user.name "JUNBUNG-droid"

          # result.txt 파일이 존재하는지 확인
          if [ -f result.txt ]; then
            git add result.txt
            git commit -m "Update result.txt" || echo "Nothing to commit"

            # git remote URL을 토큰 기반 URL로 교체
            git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git

            # push
            git push origin HEAD:${{ github.ref }}
          else
            echo "result.txt 파일이 존재하지 않습니다."
          fi

