name: Run ask_gemini.py every hour

on:
  schedule:
    - cron: '0 * * * *'      # 매시간 정각마다 실행
  workflow_dispatch:        # 수동 실행도 가능

permissions:
  contents: write           # 저장소 내용 수정 권한
  actions: read             # 액션 수정 권한

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python ask_gemini.py

      - name: Commit generated .txt files
        run: |
          # Git 사용자 설정
          git config --global user.email "rimblee2000@gmail.com"
          git config --global user.name "JUNBUNG-droid"

          # 워크스페이스 루트로 이동 (optional)
          cd $GITHUB_WORKSPACE

          # 모든 .txt 파일 스테이징
          git add *.txt

          # 커밋 (변경 없으면 넘어감)
          git commit -m "Update feedback files" || echo "Nothing to commit"

          # 토큰 기반 원격 URL 세팅
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git

          # 변경된 브랜치로 푸시
          git push origin HEAD:${{ github.ref#refs/heads/ }}  


