name: Run ask_gemini.py every hour

on:
  schedule:
    - cron: '0 14 * * *'  # 매일 밤 11시(KST)에 실행
  workflow_dispatch:      # 수동으로도 실행 가능

permissions:
  contents: write  # 저장소 내용 수정 권한 설정
  actions: read    # 액션 수정 권한 설정

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python ask_gemini.py

      - name: Ensure git is initialized and commit feedback files
        run: |
          git config --global user.email "rimblee2000@gmail.com"
          git config --global user.name "JUNBUNG-droid"
      
          # 변경된 .txt 파일 모두 스테이징
          git add *.txt
      
          # 변경사항이 있으면 커밋
          git commit -m "Update feedback files" || echo "Nothing to commit"
      
          # 토큰을 이용한 푸시
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref }}


